version: 2
jobs:
  compilar:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - checkout
      - run:
          name: Instalando dependencias de pilas
          command: make iniciar
      - run:
          name: Ejecutando test
          command: make deploy
workflows:
  version: 2
  compilar:
    jobs:
      - compilar
