version: 2
jobs:
  compilar:
    docker:
      - image: starefossen/ruby-node:2-8
    steps:
      - checkout
      - run:
          name: Instalando dependencias
          command: bundle install
      - run:
          name: Ejecutando test
          command: bundle exec jekyll build --verbose
workflows:
  version: 2
  compilar:
    jobs:
      - compilar
