version: 2
jobs:
  compilar:
    docker:
      - image: starefossen/ruby-node:2-8
    steps:
      - checkout
      - run:
          name: Instalando dependencias
          command: bundle install
      - run:
          name: Generando sitio html
          command: bundle exec jekyll build --verbose
      - run: echo -e "Host hugoruscitti.com.ar\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
      - run: echo -e "Host examplelab.com.ar\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
      - run: echo -e "Host pilas-engine.com.ar\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
      - run:
          name: Subiendo a dokku
          command: make deploy_a_produccion
workflows:
  version: 2
  compilar:
    jobs:
      - compilar
