version: 2
jobs:
  compilar:
    docker:
      - image: starefossen/ruby-node:2-8
    steps:
      - checkout
      - run:
          name: Instalando dependencias
          command: bundle install
      - run:
          name: Generando sitio html
          command: bundle exec jekyll build --verbose
      - run:
          name: Instalando surge
          command: npm install surge -g
      - run:
          name: Subiendo a surge
          command: surge _site/ -d sitio-web-de-pilas-engine.surge.sh
      - run:
          name: Subiendo a dokku
          command: make deploy_a_produccion
workflows:
  version: 2
  compilar:
    jobs:
      - compilar
